/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CreateDriverRequest {
  'name' : string,
  'assignedVehicleId' : [] | [VehicleId],
  'phone' : string,
  'principalId' : [] | [Principal],
}
export interface CreateShipmentRequest {
  'customerName' : string,
  'deliveryAddress' : string,
  'itemDescription' : string,
  'customerPhone' : string,
  'pickupAddress' : string,
  'weightKg' : number,
}
export interface CreateVehicleRequest {
  'licensePlate' : string,
  'capacityKg' : number,
}
export interface Driver {
  'id' : DriverId,
  'name' : string,
  'isActive' : boolean,
  'assignedVehicleId' : [] | [VehicleId],
  'phone' : string,
  'principalId' : [] | [Principal],
}
export type DriverId = bigint;
export interface GpsCoordinates {
  'lat' : number,
  'lng' : number,
  'capturedAt' : Timestamp,
}
export interface Shipment {
  'id' : ShipmentId,
  'customerName' : string,
  'trackingCode' : TrackingCode,
  'deliveryAddress' : string,
  'itemDescription' : string,
  'customerPhone' : string,
  'createdAt' : Timestamp,
  'statusHistory' : Array<StatusEvent>,
  'assignedDriverId' : [] | [DriverId],
  'pickupAddress' : string,
  'weightKg' : number,
  'assignedVehicleId' : [] | [VehicleId],
  'lastGps' : [] | [GpsCoordinates],
  'currentStatus' : ShipmentStatus,
}
export type ShipmentId = bigint;
export type ShipmentStatus = { 'assigned' : null } |
  { 'pending' : null } |
  { 'inTransit' : null } |
  { 'pickedUp' : null } |
  { 'delivered' : null } |
  { 'failed' : null };
export interface StaffProfile {
  'name' : string,
  'role' : StaffRole,
  'principalId' : Principal,
}
export type StaffRole = { 'admin' : null } |
  { 'dispatcher' : null } |
  { 'driver' : null };
export interface StatusEvent {
  'status' : ShipmentStatus,
  'staffOnly' : boolean,
  'note' : [] | [string],
  'timestamp' : Timestamp,
}
export type Timestamp = bigint;
export type TrackingCode = string;
export interface UpdateStatusRequest {
  'gps' : [] | [GpsCoordinates],
  'status' : ShipmentStatus,
  'staffOnly' : boolean,
  'note' : [] | [string],
  'shipmentId' : ShipmentId,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Vehicle {
  'id' : VehicleId,
  'status' : VehicleStatus,
  'licensePlate' : string,
  'capacityKg' : number,
}
export type VehicleId = bigint;
export type VehicleStatus = { 'available' : null } |
  { 'maintenance' : null } |
  { 'inUse' : null };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addShipmentNote' : ActorMethod<[ShipmentId, string, boolean], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignDriverToShipment' : ActorMethod<
    [ShipmentId, DriverId, [] | [VehicleId]],
    undefined
  >,
  'createDriver' : ActorMethod<[CreateDriverRequest], Driver>,
  'createVehicle' : ActorMethod<[CreateVehicleRequest], Vehicle>,
  'deactivateDriver' : ActorMethod<[DriverId], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [StaffProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDriver' : ActorMethod<[DriverId], [] | [Driver]>,
  'getShipment' : ActorMethod<[ShipmentId], [] | [Shipment]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [StaffProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllShipments' : ActorMethod<[], Array<Shipment>>,
  'listDrivers' : ActorMethod<[], Array<Driver>>,
  'listStaffProfiles' : ActorMethod<[], Array<StaffProfile>>,
  'listVehicles' : ActorMethod<[], Array<Vehicle>>,
  'pushGpsUpdate' : ActorMethod<[ShipmentId, GpsCoordinates], undefined>,
  'saveCallerUserProfile' : ActorMethod<[StaffProfile], undefined>,
  'submitOrder' : ActorMethod<[CreateShipmentRequest], Shipment>,
  'trackShipment' : ActorMethod<[TrackingCode], [] | [Shipment]>,
  'updateDriver' : ActorMethod<[DriverId, CreateDriverRequest], undefined>,
  'updateShipmentStatus' : ActorMethod<[UpdateStatusRequest], undefined>,
  'updateVehicleStatus' : ActorMethod<[VehicleId, VehicleStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];