/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ShipmentId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const DriverId = IDL.Nat;
export const VehicleId = IDL.Nat;
export const CreateDriverRequest = IDL.Record({
  'name' : IDL.Text,
  'assignedVehicleId' : IDL.Opt(VehicleId),
  'phone' : IDL.Text,
  'principalId' : IDL.Opt(IDL.Principal),
});
export const Driver = IDL.Record({
  'id' : DriverId,
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
  'assignedVehicleId' : IDL.Opt(VehicleId),
  'phone' : IDL.Text,
  'principalId' : IDL.Opt(IDL.Principal),
});
export const CreateVehicleRequest = IDL.Record({
  'licensePlate' : IDL.Text,
  'capacityKg' : IDL.Float64,
});
export const VehicleStatus = IDL.Variant({
  'available' : IDL.Null,
  'maintenance' : IDL.Null,
  'inUse' : IDL.Null,
});
export const Vehicle = IDL.Record({
  'id' : VehicleId,
  'status' : VehicleStatus,
  'licensePlate' : IDL.Text,
  'capacityKg' : IDL.Float64,
});
export const StaffRole = IDL.Variant({
  'admin' : IDL.Null,
  'dispatcher' : IDL.Null,
  'driver' : IDL.Null,
});
export const StaffProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : StaffRole,
  'principalId' : IDL.Principal,
});
export const TrackingCode = IDL.Text;
export const Timestamp = IDL.Int;
export const ShipmentStatus = IDL.Variant({
  'assigned' : IDL.Null,
  'pending' : IDL.Null,
  'inTransit' : IDL.Null,
  'pickedUp' : IDL.Null,
  'delivered' : IDL.Null,
  'failed' : IDL.Null,
});
export const StatusEvent = IDL.Record({
  'status' : ShipmentStatus,
  'staffOnly' : IDL.Bool,
  'note' : IDL.Opt(IDL.Text),
  'timestamp' : Timestamp,
});
export const GpsCoordinates = IDL.Record({
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
  'capturedAt' : Timestamp,
});
export const Shipment = IDL.Record({
  'id' : ShipmentId,
  'customerName' : IDL.Text,
  'trackingCode' : TrackingCode,
  'deliveryAddress' : IDL.Text,
  'itemDescription' : IDL.Text,
  'customerPhone' : IDL.Text,
  'createdAt' : Timestamp,
  'statusHistory' : IDL.Vec(StatusEvent),
  'assignedDriverId' : IDL.Opt(DriverId),
  'pickupAddress' : IDL.Text,
  'weightKg' : IDL.Float64,
  'assignedVehicleId' : IDL.Opt(VehicleId),
  'lastGps' : IDL.Opt(GpsCoordinates),
  'currentStatus' : ShipmentStatus,
});
export const CreateShipmentRequest = IDL.Record({
  'customerName' : IDL.Text,
  'deliveryAddress' : IDL.Text,
  'itemDescription' : IDL.Text,
  'customerPhone' : IDL.Text,
  'pickupAddress' : IDL.Text,
  'weightKg' : IDL.Float64,
});
export const UpdateStatusRequest = IDL.Record({
  'gps' : IDL.Opt(GpsCoordinates),
  'status' : ShipmentStatus,
  'staffOnly' : IDL.Bool,
  'note' : IDL.Opt(IDL.Text),
  'shipmentId' : ShipmentId,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addShipmentNote' : IDL.Func([ShipmentId, IDL.Text, IDL.Bool], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignDriverToShipment' : IDL.Func(
      [ShipmentId, DriverId, IDL.Opt(VehicleId)],
      [],
      [],
    ),
  'createDriver' : IDL.Func([CreateDriverRequest], [Driver], []),
  'createVehicle' : IDL.Func([CreateVehicleRequest], [Vehicle], []),
  'deactivateDriver' : IDL.Func([DriverId], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(StaffProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDriver' : IDL.Func([DriverId], [IDL.Opt(Driver)], ['query']),
  'getShipment' : IDL.Func([ShipmentId], [IDL.Opt(Shipment)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(StaffProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllShipments' : IDL.Func([], [IDL.Vec(Shipment)], ['query']),
  'listDrivers' : IDL.Func([], [IDL.Vec(Driver)], ['query']),
  'listStaffProfiles' : IDL.Func([], [IDL.Vec(StaffProfile)], ['query']),
  'listVehicles' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
  'pushGpsUpdate' : IDL.Func([ShipmentId, GpsCoordinates], [], []),
  'saveCallerUserProfile' : IDL.Func([StaffProfile], [], []),
  'submitOrder' : IDL.Func([CreateShipmentRequest], [Shipment], []),
  'trackShipment' : IDL.Func([TrackingCode], [IDL.Opt(Shipment)], ['query']),
  'updateDriver' : IDL.Func([DriverId, CreateDriverRequest], [], []),
  'updateShipmentStatus' : IDL.Func([UpdateStatusRequest], [], []),
  'updateVehicleStatus' : IDL.Func([VehicleId, VehicleStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ShipmentId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const DriverId = IDL.Nat;
  const VehicleId = IDL.Nat;
  const CreateDriverRequest = IDL.Record({
    'name' : IDL.Text,
    'assignedVehicleId' : IDL.Opt(VehicleId),
    'phone' : IDL.Text,
    'principalId' : IDL.Opt(IDL.Principal),
  });
  const Driver = IDL.Record({
    'id' : DriverId,
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
    'assignedVehicleId' : IDL.Opt(VehicleId),
    'phone' : IDL.Text,
    'principalId' : IDL.Opt(IDL.Principal),
  });
  const CreateVehicleRequest = IDL.Record({
    'licensePlate' : IDL.Text,
    'capacityKg' : IDL.Float64,
  });
  const VehicleStatus = IDL.Variant({
    'available' : IDL.Null,
    'maintenance' : IDL.Null,
    'inUse' : IDL.Null,
  });
  const Vehicle = IDL.Record({
    'id' : VehicleId,
    'status' : VehicleStatus,
    'licensePlate' : IDL.Text,
    'capacityKg' : IDL.Float64,
  });
  const StaffRole = IDL.Variant({
    'admin' : IDL.Null,
    'dispatcher' : IDL.Null,
    'driver' : IDL.Null,
  });
  const StaffProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : StaffRole,
    'principalId' : IDL.Principal,
  });
  const TrackingCode = IDL.Text;
  const Timestamp = IDL.Int;
  const ShipmentStatus = IDL.Variant({
    'assigned' : IDL.Null,
    'pending' : IDL.Null,
    'inTransit' : IDL.Null,
    'pickedUp' : IDL.Null,
    'delivered' : IDL.Null,
    'failed' : IDL.Null,
  });
  const StatusEvent = IDL.Record({
    'status' : ShipmentStatus,
    'staffOnly' : IDL.Bool,
    'note' : IDL.Opt(IDL.Text),
    'timestamp' : Timestamp,
  });
  const GpsCoordinates = IDL.Record({
    'lat' : IDL.Float64,
    'lng' : IDL.Float64,
    'capturedAt' : Timestamp,
  });
  const Shipment = IDL.Record({
    'id' : ShipmentId,
    'customerName' : IDL.Text,
    'trackingCode' : TrackingCode,
    'deliveryAddress' : IDL.Text,
    'itemDescription' : IDL.Text,
    'customerPhone' : IDL.Text,
    'createdAt' : Timestamp,
    'statusHistory' : IDL.Vec(StatusEvent),
    'assignedDriverId' : IDL.Opt(DriverId),
    'pickupAddress' : IDL.Text,
    'weightKg' : IDL.Float64,
    'assignedVehicleId' : IDL.Opt(VehicleId),
    'lastGps' : IDL.Opt(GpsCoordinates),
    'currentStatus' : ShipmentStatus,
  });
  const CreateShipmentRequest = IDL.Record({
    'customerName' : IDL.Text,
    'deliveryAddress' : IDL.Text,
    'itemDescription' : IDL.Text,
    'customerPhone' : IDL.Text,
    'pickupAddress' : IDL.Text,
    'weightKg' : IDL.Float64,
  });
  const UpdateStatusRequest = IDL.Record({
    'gps' : IDL.Opt(GpsCoordinates),
    'status' : ShipmentStatus,
    'staffOnly' : IDL.Bool,
    'note' : IDL.Opt(IDL.Text),
    'shipmentId' : ShipmentId,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addShipmentNote' : IDL.Func([ShipmentId, IDL.Text, IDL.Bool], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignDriverToShipment' : IDL.Func(
        [ShipmentId, DriverId, IDL.Opt(VehicleId)],
        [],
        [],
      ),
    'createDriver' : IDL.Func([CreateDriverRequest], [Driver], []),
    'createVehicle' : IDL.Func([CreateVehicleRequest], [Vehicle], []),
    'deactivateDriver' : IDL.Func([DriverId], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(StaffProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDriver' : IDL.Func([DriverId], [IDL.Opt(Driver)], ['query']),
    'getShipment' : IDL.Func([ShipmentId], [IDL.Opt(Shipment)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(StaffProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllShipments' : IDL.Func([], [IDL.Vec(Shipment)], ['query']),
    'listDrivers' : IDL.Func([], [IDL.Vec(Driver)], ['query']),
    'listStaffProfiles' : IDL.Func([], [IDL.Vec(StaffProfile)], ['query']),
    'listVehicles' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
    'pushGpsUpdate' : IDL.Func([ShipmentId, GpsCoordinates], [], []),
    'saveCallerUserProfile' : IDL.Func([StaffProfile], [], []),
    'submitOrder' : IDL.Func([CreateShipmentRequest], [Shipment], []),
    'trackShipment' : IDL.Func([TrackingCode], [IDL.Opt(Shipment)], ['query']),
    'updateDriver' : IDL.Func([DriverId, CreateDriverRequest], [], []),
    'updateShipmentStatus' : IDL.Func([UpdateStatusRequest], [], []),
    'updateVehicleStatus' : IDL.Func([VehicleId, VehicleStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };