/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CreateShipmentRequest {
    customerName: string;
    deliveryAddress: string;
    itemDescription: string;
    customerPhone: string;
    pickupAddress: string;
    weightKg: number;
}
export type Timestamp = bigint;
export type VehicleId = bigint;
export interface UpdateStatusRequest {
    gps?: GpsCoordinates;
    status: ShipmentStatus;
    staffOnly: boolean;
    note?: string;
    shipmentId: ShipmentId;
}
export interface Shipment {
    id: ShipmentId;
    customerName: string;
    trackingCode: TrackingCode;
    deliveryAddress: string;
    itemDescription: string;
    customerPhone: string;
    createdAt: Timestamp;
    statusHistory: Array<StatusEvent>;
    assignedDriverId?: DriverId;
    pickupAddress: string;
    weightKg: number;
    assignedVehicleId?: VehicleId;
    lastGps?: GpsCoordinates;
    currentStatus: ShipmentStatus;
}
export interface Driver {
    id: DriverId;
    name: string;
    isActive: boolean;
    assignedVehicleId?: VehicleId;
    phone: string;
    principalId?: Principal;
}
export interface StaffProfile {
    name: string;
    role: StaffRole;
    principalId: Principal;
}
export interface Vehicle {
    id: VehicleId;
    status: VehicleStatus;
    licensePlate: string;
    capacityKg: number;
}
export type TrackingCode = string;
export type ShipmentId = bigint;
export interface GpsCoordinates {
    lat: number;
    lng: number;
    capturedAt: Timestamp;
}
export type DriverId = bigint;
export interface CreateDriverRequest {
    name: string;
    assignedVehicleId?: VehicleId;
    phone: string;
    principalId?: Principal;
}
export interface StatusEvent {
    status: ShipmentStatus;
    staffOnly: boolean;
    note?: string;
    timestamp: Timestamp;
}
export interface CreateVehicleRequest {
    licensePlate: string;
    capacityKg: number;
}
export enum ShipmentStatus {
    assigned = "assigned",
    pending = "pending",
    inTransit = "inTransit",
    pickedUp = "pickedUp",
    delivered = "delivered",
    failed = "failed"
}
export enum StaffRole {
    admin = "admin",
    dispatcher = "dispatcher",
    driver = "driver"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum VehicleStatus {
    available = "available",
    maintenance = "maintenance",
    inUse = "inUse"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    addShipmentNote(shipmentId: ShipmentId, note: string, staffOnly: boolean): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignDriverToShipment(shipmentId: ShipmentId, driverId: DriverId, vehicleId: VehicleId | null): Promise<void>;
    createDriver(req: CreateDriverRequest): Promise<Driver>;
    createVehicle(req: CreateVehicleRequest): Promise<Vehicle>;
    deactivateDriver(id: DriverId): Promise<void>;
    getCallerUserProfile(): Promise<StaffProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDriver(id: DriverId): Promise<Driver | null>;
    getShipment(id: ShipmentId): Promise<Shipment | null>;
    getUserProfile(user: Principal): Promise<StaffProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listAllShipments(): Promise<Array<Shipment>>;
    listDrivers(): Promise<Array<Driver>>;
    listStaffProfiles(): Promise<Array<StaffProfile>>;
    listVehicles(): Promise<Array<Vehicle>>;
    pushGpsUpdate(shipmentId: ShipmentId, coords: GpsCoordinates): Promise<void>;
    saveCallerUserProfile(profile: StaffProfile): Promise<void>;
    submitOrder(req: CreateShipmentRequest): Promise<Shipment>;
    trackShipment(trackingCode: TrackingCode): Promise<Shipment | null>;
    updateDriver(id: DriverId, req: CreateDriverRequest): Promise<void>;
    updateShipmentStatus(req: UpdateStatusRequest): Promise<void>;
    updateVehicleStatus(id: VehicleId, status: VehicleStatus): Promise<void>;
}
import type { CreateDriverRequest as _CreateDriverRequest, Driver as _Driver, DriverId as _DriverId, GpsCoordinates as _GpsCoordinates, Shipment as _Shipment, ShipmentId as _ShipmentId, ShipmentStatus as _ShipmentStatus, StaffProfile as _StaffProfile, StaffRole as _StaffRole, StatusEvent as _StatusEvent, Timestamp as _Timestamp, TrackingCode as _TrackingCode, UpdateStatusRequest as _UpdateStatusRequest, UserRole as _UserRole, Vehicle as _Vehicle, VehicleId as _VehicleId, VehicleStatus as _VehicleStatus } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addShipmentNote(arg0: ShipmentId, arg1: string, arg2: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addShipmentNote(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addShipmentNote(arg0, arg1, arg2);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignDriverToShipment(arg0: ShipmentId, arg1: DriverId, arg2: VehicleId | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignDriverToShipment(arg0, arg1, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignDriverToShipment(arg0, arg1, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async createDriver(arg0: CreateDriverRequest): Promise<Driver> {
        if (this.processError) {
            try {
                const result = await this.actor.createDriver(to_candid_CreateDriverRequest_n4(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Driver_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDriver(to_candid_CreateDriverRequest_n4(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Driver_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async createVehicle(arg0: CreateVehicleRequest): Promise<Vehicle> {
        if (this.processError) {
            try {
                const result = await this.actor.createVehicle(arg0);
                return from_candid_Vehicle_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createVehicle(arg0);
            return from_candid_Vehicle_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async deactivateDriver(arg0: DriverId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deactivateDriver(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deactivateDriver(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<StaffProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDriver(arg0: DriverId): Promise<Driver | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDriver(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDriver(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getShipment(arg0: ShipmentId): Promise<Shipment | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getShipment(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShipment(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<StaffProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listAllShipments(): Promise<Array<Shipment>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllShipments();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllShipments();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async listDrivers(): Promise<Array<Driver>> {
        if (this.processError) {
            try {
                const result = await this.actor.listDrivers();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listDrivers();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async listStaffProfiles(): Promise<Array<StaffProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.listStaffProfiles();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listStaffProfiles();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async listVehicles(): Promise<Array<Vehicle>> {
        if (this.processError) {
            try {
                const result = await this.actor.listVehicles();
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listVehicles();
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async pushGpsUpdate(arg0: ShipmentId, arg1: GpsCoordinates): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.pushGpsUpdate(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.pushGpsUpdate(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: StaffProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_StaffProfile_n37(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_StaffProfile_n37(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitOrder(arg0: CreateShipmentRequest): Promise<Shipment> {
        if (this.processError) {
            try {
                const result = await this.actor.submitOrder(arg0);
                return from_candid_Shipment_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitOrder(arg0);
            return from_candid_Shipment_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async trackShipment(arg0: TrackingCode): Promise<Shipment | null> {
        if (this.processError) {
            try {
                const result = await this.actor.trackShipment(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.trackShipment(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateDriver(arg0: DriverId, arg1: CreateDriverRequest): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDriver(arg0, to_candid_CreateDriverRequest_n4(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDriver(arg0, to_candid_CreateDriverRequest_n4(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateShipmentStatus(arg0: UpdateStatusRequest): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateShipmentStatus(to_candid_UpdateStatusRequest_n41(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateShipmentStatus(to_candid_UpdateStatusRequest_n41(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateVehicleStatus(arg0: VehicleId, arg1: VehicleStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVehicleStatus(arg0, to_candid_VehicleStatus_n45(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVehicleStatus(arg0, to_candid_VehicleStatus_n45(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_Driver_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Driver): Driver {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_ShipmentStatus_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ShipmentStatus): ShipmentStatus {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_Shipment_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Shipment): Shipment {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_StaffProfile_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StaffProfile): StaffProfile {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_StaffRole_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StaffRole): StaffRole {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_StatusEvent_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StatusEvent): StatusEvent {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_VehicleStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VehicleStatus): VehicleStatus {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Vehicle_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Vehicle): Vehicle {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StaffProfile]): StaffProfile | null {
    return value.length === 0 ? null : from_candid_StaffProfile_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Driver]): Driver | null {
    return value.length === 0 ? null : from_candid_Driver_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Shipment]): Shipment | null {
    return value.length === 0 ? null : from_candid_Shipment_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DriverId]): DriverId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GpsCoordinates]): GpsCoordinates | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_VehicleId]): VehicleId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _VehicleId;
    status: _VehicleStatus;
    licensePlate: string;
    capacityKg: number;
}): {
    id: VehicleId;
    status: VehicleStatus;
    licensePlate: string;
    capacityKg: number;
} {
    return {
        id: value.id,
        status: from_candid_VehicleStatus_n12(_uploadFile, _downloadFile, value.status),
        licensePlate: value.licensePlate,
        capacityKg: value.capacityKg
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: _StaffRole;
    principalId: Principal;
}): {
    name: string;
    role: StaffRole;
    principalId: Principal;
} {
    return {
        name: value.name,
        role: from_candid_StaffRole_n17(_uploadFile, _downloadFile, value.role),
        principalId: value.principalId
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ShipmentId;
    customerName: string;
    trackingCode: _TrackingCode;
    deliveryAddress: string;
    itemDescription: string;
    customerPhone: string;
    createdAt: _Timestamp;
    statusHistory: Array<_StatusEvent>;
    assignedDriverId: [] | [_DriverId];
    pickupAddress: string;
    weightKg: number;
    assignedVehicleId: [] | [_VehicleId];
    lastGps: [] | [_GpsCoordinates];
    currentStatus: _ShipmentStatus;
}): {
    id: ShipmentId;
    customerName: string;
    trackingCode: TrackingCode;
    deliveryAddress: string;
    itemDescription: string;
    customerPhone: string;
    createdAt: Timestamp;
    statusHistory: Array<StatusEvent>;
    assignedDriverId?: DriverId;
    pickupAddress: string;
    weightKg: number;
    assignedVehicleId?: VehicleId;
    lastGps?: GpsCoordinates;
    currentStatus: ShipmentStatus;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        trackingCode: value.trackingCode,
        deliveryAddress: value.deliveryAddress,
        itemDescription: value.itemDescription,
        customerPhone: value.customerPhone,
        createdAt: value.createdAt,
        statusHistory: from_candid_vec_n25(_uploadFile, _downloadFile, value.statusHistory),
        assignedDriverId: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.assignedDriverId)),
        pickupAddress: value.pickupAddress,
        weightKg: value.weightKg,
        assignedVehicleId: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.assignedVehicleId)),
        lastGps: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.lastGps)),
        currentStatus: from_candid_ShipmentStatus_n28(_uploadFile, _downloadFile, value.currentStatus)
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ShipmentStatus;
    staffOnly: boolean;
    note: [] | [string];
    timestamp: _Timestamp;
}): {
    status: ShipmentStatus;
    staffOnly: boolean;
    note?: string;
    timestamp: Timestamp;
} {
    return {
        status: from_candid_ShipmentStatus_n28(_uploadFile, _downloadFile, value.status),
        staffOnly: value.staffOnly,
        note: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.note)),
        timestamp: value.timestamp
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _DriverId;
    name: string;
    isActive: boolean;
    assignedVehicleId: [] | [_VehicleId];
    phone: string;
    principalId: [] | [Principal];
}): {
    id: DriverId;
    name: string;
    isActive: boolean;
    assignedVehicleId?: VehicleId;
    phone: string;
    principalId?: Principal;
} {
    return {
        id: value.id,
        name: value.name,
        isActive: value.isActive,
        assignedVehicleId: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.assignedVehicleId)),
        phone: value.phone,
        principalId: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.principalId))
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    available: null;
} | {
    maintenance: null;
} | {
    inUse: null;
}): VehicleStatus {
    return "available" in value ? VehicleStatus.available : "maintenance" in value ? VehicleStatus.maintenance : "inUse" in value ? VehicleStatus.inUse : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    dispatcher: null;
} | {
    driver: null;
}): StaffRole {
    return "admin" in value ? StaffRole.admin : "dispatcher" in value ? StaffRole.dispatcher : "driver" in value ? StaffRole.driver : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    assigned: null;
} | {
    pending: null;
} | {
    inTransit: null;
} | {
    pickedUp: null;
} | {
    delivered: null;
} | {
    failed: null;
}): ShipmentStatus {
    return "assigned" in value ? ShipmentStatus.assigned : "pending" in value ? ShipmentStatus.pending : "inTransit" in value ? ShipmentStatus.inTransit : "pickedUp" in value ? ShipmentStatus.pickedUp : "delivered" in value ? ShipmentStatus.delivered : "failed" in value ? ShipmentStatus.failed : value;
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StatusEvent>): Array<StatusEvent> {
    return value.map((x)=>from_candid_StatusEvent_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Shipment>): Array<Shipment> {
    return value.map((x)=>from_candid_Shipment_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Driver>): Array<Driver> {
    return value.map((x)=>from_candid_Driver_n6(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StaffProfile>): Array<StaffProfile> {
    return value.map((x)=>from_candid_StaffProfile_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Vehicle>): Array<Vehicle> {
    return value.map((x)=>from_candid_Vehicle_n10(_uploadFile, _downloadFile, x));
}
function to_candid_CreateDriverRequest_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateDriverRequest): _CreateDriverRequest {
    return to_candid_record_n5(_uploadFile, _downloadFile, value);
}
function to_candid_ShipmentStatus_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ShipmentStatus): _ShipmentStatus {
    return to_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function to_candid_StaffProfile_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StaffProfile): _StaffProfile {
    return to_candid_record_n38(_uploadFile, _downloadFile, value);
}
function to_candid_StaffRole_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StaffRole): _StaffRole {
    return to_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateStatusRequest_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateStatusRequest): _UpdateStatusRequest {
    return to_candid_record_n42(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_VehicleStatus_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VehicleStatus): _VehicleStatus {
    return to_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VehicleId | null): [] | [_VehicleId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: StaffRole;
    principalId: Principal;
}): {
    name: string;
    role: _StaffRole;
    principalId: Principal;
} {
    return {
        name: value.name,
        role: to_candid_StaffRole_n39(_uploadFile, _downloadFile, value.role),
        principalId: value.principalId
    };
}
function to_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    gps?: GpsCoordinates;
    status: ShipmentStatus;
    staffOnly: boolean;
    note?: string;
    shipmentId: ShipmentId;
}): {
    gps: [] | [_GpsCoordinates];
    status: _ShipmentStatus;
    staffOnly: boolean;
    note: [] | [string];
    shipmentId: _ShipmentId;
} {
    return {
        gps: value.gps ? candid_some(value.gps) : candid_none(),
        status: to_candid_ShipmentStatus_n43(_uploadFile, _downloadFile, value.status),
        staffOnly: value.staffOnly,
        note: value.note ? candid_some(value.note) : candid_none(),
        shipmentId: value.shipmentId
    };
}
function to_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    assignedVehicleId?: VehicleId;
    phone: string;
    principalId?: Principal;
}): {
    name: string;
    assignedVehicleId: [] | [_VehicleId];
    phone: string;
    principalId: [] | [Principal];
} {
    return {
        name: value.name,
        assignedVehicleId: value.assignedVehicleId ? candid_some(value.assignedVehicleId) : candid_none(),
        phone: value.phone,
        principalId: value.principalId ? candid_some(value.principalId) : candid_none()
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StaffRole): {
    admin: null;
} | {
    dispatcher: null;
} | {
    driver: null;
} {
    return value == StaffRole.admin ? {
        admin: null
    } : value == StaffRole.dispatcher ? {
        dispatcher: null
    } : value == StaffRole.driver ? {
        driver: null
    } : value;
}
function to_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ShipmentStatus): {
    assigned: null;
} | {
    pending: null;
} | {
    inTransit: null;
} | {
    pickedUp: null;
} | {
    delivered: null;
} | {
    failed: null;
} {
    return value == ShipmentStatus.assigned ? {
        assigned: null
    } : value == ShipmentStatus.pending ? {
        pending: null
    } : value == ShipmentStatus.inTransit ? {
        inTransit: null
    } : value == ShipmentStatus.pickedUp ? {
        pickedUp: null
    } : value == ShipmentStatus.delivered ? {
        delivered: null
    } : value == ShipmentStatus.failed ? {
        failed: null
    } : value;
}
function to_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VehicleStatus): {
    available: null;
} | {
    maintenance: null;
} | {
    inUse: null;
} {
    return value == VehicleStatus.available ? {
        available: null
    } : value == VehicleStatus.maintenance ? {
        maintenance: null
    } : value == VehicleStatus.inUse ? {
        inUse: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
